# -*- coding: utf-8 -*-
"""misprimerasfunciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dmk8hEjeVUxTn2r37rNI5KO5XvpGNLx4
"""

"""
Este archivo contiene ejemplos de funciones que serán usadas en otro archivo.
"""
# Función "estéril" que imprime un objeto
def imprime(c):
    """Imprime el valor de la variable c.

    Args:
         c (any): El valor que se imprimirá.

    Returns:
          None

    """
    print(c)
    
# Función "fértil" que retorna el resultado de un cálculo
def area_cuadrado(lado):
    """Calcula el área de un cuadrado.

    Args:
       lado (float or int): La longitud del lado del cuadrado.

    Returns:
       float or int: El área del cuadrado.

    """
    # Calcular el área del cuadrado
    areacuadrado = lado ** 2

    # Devolver el área del cuadrado
    return areacuadrado 

# función "fértil" que retorna una lista
def tusDatos():
    """Solicita al usuario que ingrese su nombre y su programa curricular, y devuelve una 
    lista con estos datos.

    Args:
        None

    Returns:
        list: Una lista que contiene el nombre y el programa curricular ingresados por el usuario.

    """

    # Crear una lista
    datos = []

    # Solicitar al usuario que ingrese su nombre
    name = input("Por favor ingresa tu nombre: ")

    # Agregar los datos al final de la lista
    datos.append(name)

    # Solicitar al usuario que ingrese su programa curricular
    carrera = input("Por favor ingresa tu programa curricular: ")

    # Agregar los datos al final de la lista
    datos.append(carrera)

    # Devolver la lista
    return datos
