# -*- coding: utf-8 -*-
"""misprimerasfunciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dmk8hEjeVUxTn2r37rNI5KO5XvpGNLx4
"""

"""
Este archivo contiene ejemplos de funciones que serán usadas en otro archivo.
"""
# función "estéril" que imprime un objeto
def imprime(a):
  print(a)

# función "fértil" que retorna el resultado de un cálculo
def areaCua(lado):
  ac = lado ** 2
  return ac
 

# función "fértil" que retorna una lista
def tusDatos():
  datos = []
  name = input("Por favor ingresa tu nombre: ")
  datos.append(name)
  carrera = input("Por favor ingresa tu programa curricular: ")
  datos.append(carrera)
  return datos